image: ruby:2.3

cache:
  paths:
    - vendor/

before_script:
  - bundle install --path vendor

# add a job called 'test'
test:
  stage: test
  script:
    - gem install jekyll jekyll-coffeescript jekyll-feed jekyll-sitemap therubyracer execjs
    - bundle exec jekyll build -d public/
  except:
    - master # the 'test' job will affect all branches expect 'master'

pages:
  script:
  - gem install jekyll jekyll-coffeescript jekyll-feed jekyll-sitemap therubyracer execjs
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
